name: Test
on: ['push']
jobs:
  first-job:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: 🧙 Install apps with Yarn
        run: 'yarn'
      - name: 🛠 Build App
        run: 'yarn build:prod'
      - run: 'ls -al'
